### ISSUE TITLE
[BUG] FileNotFoundException in dss-server testcode

### ISSUE THREAD

**Issue by ParkSale** [ztkmkoo/dss#65]
**Describe the bug**
```
@Test
    public void testSsl() throws Exception {
        final PrivateKey privateKey = loadPrivateKeyFromFile(loadFromTestResources("ssl/private.der"));
        final X509Certificate certificate = loadX509CertificateFromFile(loadFromTestResources("ssl/private.crt"));

        final SslContext sslContext = SslContextBuilder.forServer(privateKey, SSL_PASSWORD, certificate).build();

        final DssRestServer dssRestServer = new DssRestServer("127.0.0.1", 8181, true, sslContext);
        dssRestServer
                .addDssRestService(new TestService("test", "/hi", DssRestMethodType.GET));

        stopDssRestServerAfterActivated(dssRestServer, 10 ,15);

        dssRestServer.start();

        assertTrue(dssRestServer.isShutdown());
    }
```
When I fork this repository and install, I got error in this test code
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
java.io.FileNotFoundException: C:\Users\����??\Documents\GitHub\dss\dss-server\target\jacoco.ex (������ ��θ� ã�� �� �����ϴ�)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at org.jacoco.agent.rt.internal_14f7ee5.output.FileOutput.openFile(FileOutput.java:67)
	at org.jacoco.agent.rt.internal_14f7ee5.output.FileOutput.startup(FileOutput.java:49)
	at org.jacoco.agent.rt.internal_14f7ee5.Agent.startup(Agent.java:122)
	at org.jacoco.agent.rt.internal_14f7ee5.Agent.getInstance(Agent.java:50)
	at org.jacoco.agent.rt.internal_14f7ee5.PreMain.premain(PreMain.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Running io.github.ztkmkoo.dss.server.rest.DssRestServerTest
10:34:13,857 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
10:34:13,858 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
10:34:13,858 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/C:/Users/%ec%84%b8%ec%9d%bc/Documents/GitHub/dss/dss-server/target/classes/logback.xml]
10:34:14,099 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
10:34:14,103 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
10:34:14,161 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
10:34:14,387 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This appender no longer admits a layout as a sub-component, set an encoder instead.
10:34:14,387 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
10:34:14,387 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
10:34:14,390 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
10:34:14,390 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
10:34:14,392 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
10:34:14,395 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@3954d008 - Registering current configuration as safe fallback point
2020-07-20 10:34:18 [INFO ] [Slf4jLogger.scala]applyOrElse(104) : Slf4jLogger started
2020-07-20 10:34:19 [INFO ] [DssRestServer.java]start(63) : Create actor system: akka://system
2020-07-20 10:34:19 [INFO ] [DssRestChannelInitializer.java]dssRestChannelInitializer(121) : Setup dssRestChannelInitializer
2020-07-20 10:34:19 [INFO ] [DssRestChannelInitializer.java]newAllocatedDssRestHandler(57) : freeHandlerQueue is empty. try to initialize new one: rest-handler-1
2020-07-20 10:34:19 [INFO ] [DssRestChannelInitializer.java]newAllocatedDssRestHandler(57) : freeHandlerQueue is empty. try to initialize new one: rest-handler-2
2020-07-20 10:34:19 [INFO ] [DssRestPathResolver.java]lambda$null$0(62) : Add mapping GET /hi to test
2020-07-20 10:34:19 [INFO ] [DssRestHandler.java]dssRestHandler(201) : Setup dssRestHandler: rest-handler-2
2020-07-20 10:34:19 [INFO ] [DssRestHandler.java]dssRestHandler(201) : Setup dssRestHandler: rest-handler-1
2020-07-20 10:34:23 [INFO ] [DssRestServer.java]stop(95) : Channel try to close. [Active: true][Open: true]
2020-07-20 10:34:23 [INFO ] [DssRestServer.java]stop(101) : Actor system try to terminate
2020-07-20 10:34:23 [INFO ] [DssRestServer.java]start(80) : Shut down worker and boss group gracefully
2020-07-20 10:34:23 [INFO ] [Slf4jLogger.scala]applyOrElse(104) : Slf4jLogger started
2020-07-20 10:34:23 [INFO ] [DssRestChannelInitializer.java]dssRestChannelInitializer(121) : Setup dssRestChannelInitializer
2020-07-20 10:34:23 [INFO ] [DssRestServer.java]start(63) : Create actor system: akka://system
2020-07-20 10:34:23 [INFO ] [DssRestChannelInitializer.java]newAllocatedDssRestHandler(57) : freeHandlerQueue is empty. try to initialize new one: rest-handler-3
2020-07-20 10:34:23 [INFO ] [DssRestChannelInitializer.java]newAllocatedDssRestHandler(57) : freeHandlerQueue is empty. try to initialize new one: rest-handler-4
2020-07-20 10:34:23 [INFO ] [DssRestHandler.java]dssRestHandler(201) : Setup dssRestHandler: rest-handler-3
2020-07-20 10:34:23 [INFO ] [DssRestPathResolver.java]lambda$null$0(62) : Add mapping GET /hi to test
2020-07-20 10:34:23 [INFO ] [DssRestHandler.java]dssRestHandler(201) : Setup dssRestHandler: rest-handler-4
2020-07-20 10:34:23 [INFO ] [DssRestPathResolver.java]lambda$null$0(62) : Add mapping GET /hello to test2
2020-07-20 10:34:24 [INFO ] [DssRestServer.java]lambda$createActorSystem$0(89) : Actor system terminated.
2020-07-20 10:34:24 [INFO ] [DssRestServer.java]stop(95) : Channel try to close. [Active: true][Open: true]
2020-07-20 10:34:24 [INFO ] [DssRestServer.java]stop(101) : Actor system try to terminate
2020-07-20 10:34:24 [INFO ] [DssRestServer.java]start(80) : Shut down worker and boss group gracefully
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 10.656 sec <<< FAILURE!
testSsl(io.github.ztkmkoo.dss.server.rest.DssRestServerTest)  Time elapsed: 0.019 sec  <<< ERROR!
java.io.FileNotFoundException: C:\Users\%ec%84%b8%ec%9d%bc\Documents\GitHub\dss\dss-server\target\test-classes\ssl\private.der (지정된 경로를 찾을 수 없습니다)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at io.github.ztkmkoo.dss.server.rest.DssRestServerTest.loadPrivateKeyFromFile(DssRestServerTest.java:148)
	at io.github.ztkmkoo.dss.server.rest.DssRestServerTest.testSsl(DssRestServerTest.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
java.io.FileNotFoundException: C:\Users\����??\Documents\GitHub\dss\dss-server\target\jacoco.ex (������ ��θ� ã�� �� �����ϴ�)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at org.jacoco.agent.rt.internal_14f7ee5.output.FileOutput.openFile(FileOutput.java:67)
	at org.jacoco.agent.rt.internal_14f7ee5.output.FileOutput.writeExecutionData(FileOutput.java:53)
	at org.jacoco.agent.rt.internal_14f7ee5.Agent.shutdown(Agent.java:137)
	at org.jacoco.agent.rt.internal_14f7ee5.Agent$1.run(Agent.java:54)
2020-07-20 10:34:24 [INFO ] [DssRestServer.java]lambda$createActorSystem$0(89) : Actor system terminated.
Results :
Tests in error: 
  testSsl(io.github.ztkmkoo.dss.server.rest.DssRestServerTest): C:\Users\%ec%84%b8%ec%9d%bc\Documents\GitHub\dss\dss-server\target\test-classes\ssl\private.der (지정된 경로를 찾을 수 없습니다)
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0
```

**Comment by ztkmkoo** [comment]
@ParkSale Hi~

Thx reporting bug. But i run the test succeed in my environment. The code `loadPrivateKeyFromFile` is get resource file from test resources directory .
![image](https://user-images.githubusercontent.com/26991409/87898557-6ca05a80-ca89-11ea-877a-6558b017069b.png)

I need more information,your project sdk(jdk) version, and your ide version.

**Comment by ztkmkoo** [comment]
@ParkSale 
It likes encoding issue. Some error occurred when load the test resource. Can you fix the loadFromTestResources method?

``` java
package io.github.ztkmkoo.dss.server.rest;

public class DssRestServerTest {
    private static File loadFromTestResources(String path) {
        final ClassLoader classLoader = DssRestServerTest.class.getClassLoader();
        return new File(classLoader.getResource(path).getFile());
    }
}
```

**Comment by ztkmkoo** [comment]
With local user account name(not eng), mvn install was failed for creating jacoco reporing file.
We have to modify jacoco plugins configuration at pom.xml

1. property 
``` xml
<jacoco.agent.argLine></jacoco.agent.argLine>
```
2. jacoco build plugin (im not sure other version worked)
``` xml
<plugin>
  <groupId>org.jacoco</groupId>
  <artifactId>jacoco-maven-plugin</artifactId>
  <version>0.7.7.201606060606</version>
  <!-- <version>0.7.6.201602180812</version>-->
  <executions>
    <execution>
      <id>prepare-agent</id>
      <goals>
        <goal>prepare-agent</goal>
      </goals>
      <configuration>
      </configuration>
    </execution>
  </executions>
  <configuration>
    <propertyName>jacoco.agent.argLine</propertyName>
  </configuration>
</plugin>
```
3. modify maven-surefire-plugin (at least 3.0.0-M3 or 2.22.0)
``` xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-surefire-plugin</artifactId>
  <version>3.0.0-M3</version>
  <configuration>
    <argLine>${jacoco.agent.argLine}</argLine>
  </configuration>
</plugin>
```

**Comment by ztkmkoo** [comment]
ref link bout jacoco
- https://stackoverflow.com/questions/12269558/maven-jacoco-plugin-error
- https://stackoverflow.com/questions/23190107/cannot-use-jacoco-jvm-args-and-surefire-jvm-args-together-in-maven

**Comment by ParkSale** [comment]
Thank you . I solve this problem with your help and add decoding in loadFromTestResources method
